name: nals_lints
description: A new Flutter package project.
version: 0.0.1
publish_to: none

environment:
  sdk: ">=3.0.5 <4.0.0"

dependency_overrides:
  analyzer: 5.13.0

dependencies:
  custom_lint_builder: 0.5.0
  source_gen: 1.4.0
