name: domain
description: A new Flutter package project.
version: 0.0.1
publish_to: none

environment:
  sdk: ">=3.0.5 <4.0.0"
  flutter: ">=1.17.0"

dependency_overrides:
  analyzer: 5.13.0

dependencies:
  async: 2.11.0
  dartx: 1.1.0
  flutter:
    sdk: flutter
  get_it: 7.6.0
  injectable: 2.1.2
  meta: 1.9.1
  resources:
    path: ../resources
  rxdart: 0.27.7
  shared:
    path: ../shared
  tuple: 2.0.2

dev_dependencies:
  build_runner: 2.4.5
  custom_lint: 0.5.0
  flutter_lints: 2.0.1
  flutter_test:
    sdk: flutter
  freezed: 2.3.5
  freezed_annotation: 2.2.0
  injectable_generator: 2.1.6
  logging: 1.1.1
  mocktail: 0.3.0
  nals_lints:
    path: ../nals_lints
