name: app
description: A new Flutter project.
publish_to: "none"
version: 1.0.0+1
environment:
  sdk: ">=3.0.5 <4.0.0"

dependency_overrides:
  analyzer: 5.13.0

dependencies:
  async: 2.11.0
  auto_route: 7.6.0
  cached_network_image: 3.2.1
  cupertino_icons: 1.0.3
  dartx: 1.1.0
  domain:
    path: ../domain
  flutter:
    sdk: flutter
  flutter_bloc: 8.0.1
  flutter_local_notifications: 12.0.4
  flutter_localizations:
    sdk: flutter
  flutter_screenutil: 5.8.4
  flutter_svg: 2.0.7
  get_it: 7.6.0
  infinite_scroll_pagination: 4.0.0
  initializer:
    path: ../initializer
  injectable: 2.1.2
  resources:
    path: ../resources
  rxdart: 0.27.7
  shared:
    path: ../shared
  tuple: 2.0.2
dev_dependencies:
  auto_route_generator: 7.1.1
  bloc_test: 9.1.3
  build_runner: 2.4.5
  custom_lint: 0.5.0
  flutter_gen_runner: 5.3.1
  flutter_launcher_icons: 0.9.2
  flutter_lints: 2.0.1
  flutter_native_splash: 2.2.16
  flutter_test:
    sdk: flutter
  freezed: 2.3.5
  freezed_annotation: 2.2.0
  injectable_generator: 2.1.6
  logging: 1.1.1
  mocktail: 0.3.0
  nals_lints:
    path: ../nals_lints

# Config generate when build
flutter_gen:
  output: lib/resource/generated
  line_lenght: 160
  null_safety: true

  integrations:
    flutter_svg: true
    # flare_flutter: true

  assets:
    enabled: true

  fonts:
    enabled: true
  # colors:
  #   enabled: true
  #   inputs:
  #     - assets/color/colors.xml
flutter:
  uses-material-design: true
  generate: false
  assets:
    - assets/images/
#  fonts:
#    - family: Muli
#      fonts:
#        - asset: assets/fonts/Muli-Bold.ttf
#          weight: 900
#        - asset: assets/fonts/Muli-SemiBold.ttf
#          weight: 700
#        - asset: assets/fonts/Muli-Regular.ttf
#          weight: 400
