name: shared
description: A new Flutter package project.
version: 0.0.1
publish_to: none

environment:
  sdk: ">=3.0.5 <4.0.0"
  flutter: ">=1.17.0"

dependency_overrides:
  analyzer: 6.2.0

dependencies:
  android_id: 0.3.6
  async: 2.11.0
  dartx: 1.2.0
  decimal: 2.3.3
  device_info_plus: 9.1.2
  flutter:
    sdk: flutter
  flutter_cache_manager: 3.3.1
  flutter_udid: 3.0.0
  injectable: 2.3.2
  intl: 0.19.0
  mime: 1.0.5
  package_info_plus: 5.0.1
  path_provider: 2.1.2
  rxdart: 0.27.7
  timezone: 0.9.2
  url_launcher: 6.2.4

dev_dependencies:
  build_runner: 2.4.8
  custom_lint: 0.6.0
  flutter_lints: 3.0.1
  flutter_test:
    sdk: flutter
  freezed: 2.4.7
  freezed_annotation: 2.4.1
  injectable_generator: 2.4.1
  logging: 1.2.0
  mocktail: 1.0.3
  nals_lints:
    path: ../nals_lints
