name: shared
description: A new Flutter package project.
version: 0.0.1
publish_to: none

environment:
  sdk: ">=3.0.5 <4.0.0"
  flutter: ">=1.17.0"

dependency_overrides:
  analyzer: 5.13.0

dependencies:
  android_id: 0.3.3
  async: 2.11.0
  dartx: 1.1.0
  decimal: 2.1.0
  device_info_plus: 9.0.2
  flutter:
    sdk: flutter
  flutter_cache_manager: 3.3.0
  flutter_udid: 2.0.1
  injectable: 2.1.2
  intl: 0.18.1
  mime: 1.0.1
  package_info_plus: 4.0.2
  path_provider: 2.0.15
  rxdart: 0.27.7
  timezone: 0.9.0
  url_launcher: 6.0.17

dev_dependencies:
  build_runner: 2.4.5
  custom_lint: 0.5.0
  flutter_lints: 2.0.1
  flutter_test:
    sdk: flutter
  freezed: 2.3.5
  freezed_annotation: 2.2.0
  injectable_generator: 2.1.6
  logging: 1.1.1
  mocktail: 0.3.0
  nals_lints:
    path: ../nals_lints
