name: shared
description: A new Flutter package project.
version: 0.0.1
publish_to: none

environment:
  sdk: '>=3.0.5 <4.0.0'
  flutter: ">=1.17.0"

dependency_overrides:
  analyzer: 5.2.0
  build_resolvers: 2.1.0
  dart_style: 2.2.4
  sqflite: 2.0.2+1

dependencies:
  android_id: 0.3.3
  async: 2.11.0
  dartx: 1.0.0
  decimal: 2.1.0
  device_info_plus: 9.0.2
  flutter:
    sdk: flutter
  flutter_cache_manager: 3.3.0
  flutter_udid: 2.0.1
  injectable: 2.1.0
  intl: 0.18.0
  mime: 1.0.1
  package_info_plus: 4.0.2
  path_provider: 2.0.7
  rxdart: 0.26.0
  timezone: 0.9.0
  url_launcher: 6.0.17

dev_dependencies:
  build_runner: 2.4.5
  dart_code_metrics: 5.1.0
  flutter_lints: 2.0.1
  flutter_test:
    sdk: flutter
  freezed: 2.3.2
  freezed_annotation: 2.2.0
  injectable_generator: 2.1.3
  mocktail: 0.3.0
