name: CI
on:
  pull_request:
    branches: [ develop ]
  workflow_dispatch:

env:
  JAVA_VERSION: "12.x"
  FLUTTER_VERSION: "3.13.1"
  MELOS_VERSION: "3.1.0"

jobs:
  UT_format_lint_notify:
    name: Check format, lint and UT
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-java@v1
        with:
          java-version: ${{env.JAVA_VERSION}}
      - uses: subosito/flutter-action@v2
        with:
          flutter-version: ${{env.FLUTTER_VERSION}}

      - name: Add pub cache bin to PATH
        run: echo "$HOME/.pub-cache/bin" >> $GITHUB_PATH

      - name: Add pub cache to PATH
        run: echo "PUB_CACHE="$HOME/.pub-cache"" >> $GITHUB_ENV

      - name: Install melos  
        run: dart pub global activate melos ${{env.MELOS_VERSION}}
      
      - name: Run pub get and gen files
        run: make sync

      - name: Run Tests
        run: make test

      - name: Check format
        run: make format

      - name: Run custom lint
        run: make custom_lint

      - name: Run analyze
        run: make analyze
      
      - name: Run dart_code_metrics
        run: make dart_code_metrics

      # - name: Check lint app
      #   uses: dart-code-checker/dart-code-metrics-action@v2
      #   with:
      #     github_token: ${{ secrets.GITHUB_TOKEN }}
      #     relative_path: 'app'

      # - name: Check lint data
      #   uses: dart-code-checker/dart-code-metrics-action@v2
      #   with:
      #     github_token: ${{ secrets.GITHUB_TOKEN }}
      #     relative_path: 'data'

      # - name: Check lint domain
      #   uses: dart-code-checker/dart-code-metrics-action@v2
      #   with:
      #     github_token: ${{ secrets.GITHUB_TOKEN }}
      #     relative_path: 'domain'

      # - name: Check lint shared
      #   uses: dart-code-checker/dart-code-metrics-action@v2
      #   with:
      #     github_token: ${{ secrets.GITHUB_TOKEN }}
      #     relative_path: 'shared'

      # - uses: mechiru/chatwork@v2
      #   with:
      #     roomId: 251400100
      #     token: ${{ secrets.CHATWORK_API_TOKEN }}
